
spring:
    config:
       activate:
           on-profile: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.MysqlDataSource
        url: jdbc:mysql://localhost:3306/administration?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
        name:
        username: root
        password: 
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show_sql: true
        open_in_view: false
        hibernate:
            naming:
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
server:
    error:
        include-message: always
custom:
    environment: azrnic
    secretKey: changeme
    accessTokenValidityInSeconds: 300
    refreshTokenValidityInSeconds: 3600
    datasource:
        cachePrepStmts: false
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    mail:
        from: support@aleksa.co
        host: localhost
        port: 587
        username:
        password:
        starttls: true
        auth: false
